apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  name: blog
  labels:
    name: blog
spec:
  replicas: 2
  template:
    metadata:
      labels:
        name: blog
    spec:
      containers:
        - name: blog
          image: kter/blog:latest
          ports:
            - containerPort: 80
          resources:
            requests:
              cpu: 10m
        - name: stub-status-exporter
          image: fish/nginx-exporter:latest
          args: ["-nginx.scrape_uri=http://localhost/status"]
          ports:
            - containerPort: 9113
          resources:
            requests:
              cpu: 10m
