apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  name: blog
  labels:
    name: blog
spec:
  replicas: 4
  template:
    metadata:
      labels:
        name: blog
    spec:
      containers:
        - name: blog
          image: kter/blog:latest
          ports:
            - containerPort: 80
