apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  name: blog
  labels:
    name: blog
spec:
  replicas: 2
  template:
    metadata:
      labels:
        name: blog
    spec:
      containers:
        - name: blog
          image: kter/blog:latest
          ports:
            - containerPort: 80
          resources:
            requests:
              cpu: 10m
        - name: nginx-vts-exporter
          image: sophos/nginx-vts-exporter
          env:
            - name: NGINX_STATUS
              value: "http://localhost/status/format/json"
          ports:
            - containerPort: 9913
          resources:
            requests:
              cpu: 10m
