apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  name: blog
  labels:
    name: blog
    keel.sh/policy: all
    keel.sh/trigger: poll
  annotations:
    keel.sh/pollSchedule: "@every 1m"
spec:
  replicas: 2
  template:
    metadata:
      labels:
        name: blog
      annotations:
        prometheus.io/scrape: 'true'
        prometheus.io/port: '9913'
    spec:
      containers:
        - name: blog
          image: kter/blog:d881e801a7d7a406fac667ac36b9637598267b76
          ports:
            - containerPort: 80
          resources:
            requests:
              cpu: 10m
        - name: nginx-vts-exporter
          image: sophos/nginx-vts-exporter
          env:
            - name: NGINX_STATUS
              value: "http://localhost/status/format/json"
          ports:
            - containerPort: 9913
          resources:
            requests:
              cpu: 10m
