apiVersion: extensions/v1beta1
kind: Ingress
metadata:
  name: blog-ingress
  annotations:
    kubernetes.io/tls-acme: "true"
    kubernetes.io/ingress.class: "gce"
  namespace: default
spec:
  tls:
  - hosts:
    - kter.jp
    - wallet.kter.jp
    secretName: blog-tls
  rules:
  - host: kter.jp
    http:
      paths:
      - path: /
        backend:
          serviceName: wordpress
          servicePort: 80
  - host: wallet.kter.jp
    http:
      paths:
      - path: /
        backend:
          serviceName: wallet
          servicePort: 3000
  backend:
    serviceName: wallet
    servicePort: 3000
    serviceName: wordpress
    servicePort: 80
---
apiVersion: v1
kind: ConfigMap
metadata:
  name: nginx-ingress-controller
  namespace: default
data:
  enable-vts-status: 'true'
