apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  name: mysql
  labels:
    name: mysql
spec:
  replicas: 1
  template:
    metadata:
      labels:
        name: mysql
    spec:
      containers:
        - image: mysql:5.6.36
          name: mysql
          env:
            - name: MYSQL_ROOT_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: app-secrets
                  key: mysql_password
          ports:
            - containerPort: 3306
              name: mysql
          volumeMounts:
            - name: mysql-db-data
              mountPath: "/var/lib/mysql"
      volumes:
        - name: mysql-db-data
          hostPath:
            path: /data/mysql-db-data
