apiVersion: extensions/v1beta1
kind: Ingress
metadata:
  name: nginx
  annotations:
    kubernetes.io/ingress.class: "nginx"
    kubernetes.io/tls-acme: "true"
spec:
  tls:
  - secretName: kubernetes-ingress-tls
    hosts:
      - kter.jp
      - wallet.kter.jp
      - mail.ttakahashi.space
      - ttakahashi.space
  rules:
  - host: kter.jp
    http:
      paths:
      - path: /
        backend:
          serviceName: wordpress
          servicePort: 80
      - path: /*
        backend:
          serviceName: wordpress
          servicePort: 80
  - host: wallet.kter.jp
    http:
      paths:
      - path: /
        backend:
          serviceName: wallet
          servicePort: 80
      - path: /*
        backend:
          serviceName: wallet
          servicePort: 80
  - host: mail.ttakahashi.space
    http:
      paths:
      - path: "/admin"
        backend:
          serviceName: mailu-admin
          servicePort: 80
  - host: ttakahashi.space
    http:
      paths:
      - path: "/admin"
        backend:
          serviceName: mailu-admin
          servicePort: 80
