apiVersion: extensions/v1beta1
kind: Ingress
metadata:
  name: nginx
  annotations:
    kubernetes.io/ingress.class: "nginx"
    kubernetes.io/tls-acme: "true"
spec:
  tls:
  - secretName: kubernetes-ingress-tls
    hosts:
      - kter.jp
      - stg.kter.jp
      - prometheus.kter.jp
      - grafana.kter.jp
  rules:
  - host: kter.jp
    http:
      paths:
      - path: /
        backend:
          serviceName: jekyll
          servicePort: 80
      - path: /*
        backend:
          serviceName: jekyll
          servicePort: 80
  - host: stg.kter.jp
    http:
      paths:
      - path: /
        backend:
          serviceName: stg-jekyll
          servicePort: 80
      - path: /*
        backend:
          serviceName: stg-jekyll
          servicePort: 80
  - host: prometheus.kter.jp
    http:
      paths:
      - path: /
        backend:
          serviceName: prometheus-prometheus-server
          servicePort: 80
      - path: /*
        backend:
          serviceName: prometheus-prometheus-server
          servicePort: 80
  - host: grafana.kter.jp
    http:
      paths:
      - path: /
        backend:
          serviceName: grafana-grafana
          servicePort: 80
      - path: /*
        backend:
          serviceName: grafana-grafana
          servicePort: 80
