apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  name: wallet
  labels:
    name: wallet
spec:
  replicas: 1
  template:
    metadata:
      labels:
        name: wallet
    spec:
      nodeSelector:
        cloud.google.com/gke-nodepool: default-pool
      containers:
        - name: wallet
          image: docker.io/kter/wallet:0.3
          ports:
            - containerPort: 3000
          env:
            - name: SECRET_KEY_BASE
              valueFrom:
                secretKeyRef:
                  name: app-secrets
                  key: secret_key_base
            - name: WALLET_DATABASE_USER
              valueFrom:
                secretKeyRef:
                  name: app-secrets
                  key: postgres_user
            - name: WALLET_DATABASE_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: app-secrets
                  key: postgres_password
            - name: WALLET_DATABASE_HOST
              valueFrom:
                secretKeyRef:
                  name: app-secrets
                  key: postgres_host
