apiVersion: v1
kind: Service
metadata:
  name: wordpress
  labels:
    name: wordpress
spec:
  type: LoadBalancer
  loadBalancerIP: 35.185.200.190
  ports:
    - name: "80"
      port: 80
      targetPort: 80
  selector:
    name: blog
